In [1]:
import numpy as np

In [4]:
vt = np.array([27, 37])  # vetor com duas dimensões
print(vt)

[27 37]


In [5]:
type(vt)

numpy.ndarray

In [7]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
B = np.matrix(([1,2,3],[4,5,6],[7,8,9]))
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

A variável da matriz pode possuir o tipo array ou matrix. Com ambos os tipos podemos fazer as operações.

In [11]:
A1 = np.array([[1,2,4],[4,5,6],[6,7,8]])
A1

array([[1, 2, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
A1 = np.matrix(A1)   # transformando o vetor multidimensional em matrix
A1

matrix([[1, 2, 4],
        [4, 5, 6],
        [6, 7, 8]])

In [15]:
type(A1)

numpy.matrix

## Matriz Diagonal

Uma matriz quadrada é dita diagonal quando todos os elementos fora da diagonal principal forem nulos.

In [17]:
C = np.diag([1,2,3,4,5,6])

In [19]:
C = np.matrix(C)
C

matrix([[1, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0],
        [0, 0, 0, 4, 0, 0],
        [0, 0, 0, 0, 5, 0],
        [0, 0, 0, 0, 0, 6]])

Matrix linha

In [21]:
B = np.array([[2,3,4]])    #deve-se colocar um conjunto a mais de colchetes ou parênteses
B

array([[2, 3, 4]])

Matriz coluna

In [23]:
C = np.array([[2],[3],[4]])
C

array([[2],
       [3],
       [4]])

In [25]:
D = np.transpose([[1,2,3,4]])
D

array([[1],
       [2],
       [3],
       [4]])

## Matriz nula

In [27]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matriz identidade

Matriz identidade ajuda  a solucionar problemas de sistemas de equações lineares. Matriz linear é aquele em que a diagonal principal possui todos os valores iguais a 1 e os demais iguais a zero.

In [30]:
MI = np.identity(4)
MI

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Matriz Transposta

A transposta de uma matriz A, troca-see ordenadamente as linhas por colunas ou vice-versa.
A **transposição não altera a diagonal principal da matriz**

In [34]:
S = np.array([[1,2,3],[3,4,9],[5,6,7]])
S

array([[1, 2, 3],
       [3, 4, 9],
       [5, 6, 7]])

In [38]:
S1 = np.transpose(S)
S1

array([[1, 3, 5],
       [2, 4, 6],
       [3, 9, 7]])

É possível utilizar o método `.T` para criar a transposta

In [36]:
S.T

array([[1, 3, 5],
       [2, 4, 6],
       [3, 9, 7]])

In [39]:
S == S1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [40]:
(S+S1).T == S.T + S1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
(S.T).T == S

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
(10*S).T == 10*S.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
(S*S1).T == S.T * S1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])