# Sci-kit Learn

> Scikit-learn library requires input of two-dimensional numpy arrays.

## Numpy 
Use of it.

In [1]:
import numpy as np

In [3]:
array_1 = np.arange(10)
array_1.shape

(10,)

In [5]:
# dimension
array_1.ndim

1

In [8]:
#reshape
array_1 = array_1.reshape((5,2))
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
array_1.ndim

2

In [10]:
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
array_1 = array_1 + 1

In [17]:
array_2 = array_2.reshape((5,2))

In [18]:
array_1 + array_2

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

> scikit-learn expects np.float arguments in arrays.

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((5,2), dtype=np.int64)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [28]:
# np.empty to allocate memory for an arrat of specific size and dtype
np.empty((5,2), dtype= np.float64)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## indexing

In [32]:
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
array_1[0,0] # look out values, first rown and first column

1

In [35]:
array_1[0,:]  # first row

array([1, 2])

In [36]:
array_1[:,0]  # first column

array([1, 3, 5, 7, 9])

In [45]:
array_1[2:5,:]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [46]:
array_1[2:5,0]

array([5, 7, 9])

### Boolean matriz

In [56]:
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [52]:
#  mostra valores boolean
array_1 > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [51]:
# colocar em colchete para filtrar matriz boolean, mostra  número
array_1[array_1 > 5]

array([ 6,  7,  8,  9, 10])

### Operações aritméticas

In [54]:
# soma todas as entradas
array_1.sum()

55

In [55]:
# encontra a soma por linha
array_1.sum(axis=1)

array([ 3,  7, 11, 15, 19])

In [57]:
# encontra os resultados por coluna
array_1.sum(axis=0)

array([25, 30])

In [59]:
# encontra média por coluna, dtype da média é np.float64
array_1.mean(axis=0)

array([5., 6.])

### NaN valores

> scikit-learn não aceita valores `np.nan`

In [60]:
array_3 = np.array([np.nan, 0,1,2,np.nan])

In [61]:
array_3

array([nan,  0.,  1.,  2., nan])

In [62]:
# encontrar valores NaN 
np.isnan(array_3)

array([ True, False, False, False,  True])

In [63]:
#filtro, negando valores NaN
array_3[~np.isnan(array_3)]

array([0., 1., 2.])

In [65]:
#mudando os NaN para zero (filtro)
array_3[np.isnan(array_3)] = 0

🛑 Scikit-learn accepts only 2D Numpy arrays of real numbers with no missing `np.nan` values, so try to change
 `np.nan` to some value instead of throwing away data. 