In [1]:
import numpy as np

## Dimensão de Matrizes

1-D, 2-D, 3-D. `dtype` é usada para str, float, int ou número complexo.  
`.ndim` usada para conhecer a dimensão da matriz.

In [2]:
zero_d = np.array(0)
zero_d.ndim

0

In [3]:
one_d =  np.array([0,1])
one_d.ndim

1

In [4]:
two_d =  np.array([[0,1],[2,3]], dtype= int)
two_d.ndim

2

In [5]:
print(two_d)

[[0 1]
 [2 3]]


In [6]:
three_d = np.array([[[1,2],[2,3]],[[3,4],[5,6]]], dtype= float)
three_d.ndim

3

In [7]:
print(three_d)

[[[1. 2.]
  [2. 3.]]

 [[3. 4.]
  [5. 6.]]]


## Indexando Matrizes

Como nas listas, começa indexando no zero,segundo elemento é 1 e assim por diante...números negativos também é possível indexar.

`.shape` para verificar o formato da matriz.

In [8]:
exemplo = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
], dtype=int)
exemplo

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
exemplo[0][0][1]
exemplo[0,0,1]

2

In [10]:
exemplo[1][1]
exemplo[1,1]

array([10, 11, 12])

In [11]:
#negativo
exemplo[1,1,-1]
exemplo[1][1][-1]

12

In [12]:
exemplo.shape

(2, 2, 3)

In [13]:
d4 = np.array([
    [[
        [1,2,3],[4,5,6]
    ]],
    [[
        [7,8,9],[10,11,12]
    ]]
])

d4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])

In [14]:
d4.shape

(2, 1, 2, 3)

## Formatando matrizes

Usando a função `nome.reshape()`

In [15]:
E = np.array([[1,2,30],[4,5,6]])
E.shape

(2, 3)

In [16]:
E.reshape(3,2)

array([[ 1,  2],
       [30,  4],
       [ 5,  6]])

Número inpróprios ao refazer a matriz, resulta em erro.

## Concatenando Matrizes


Duas ou mais matrizes podem ser juntadas para formar um conjunto de elementos baseado no número de indexação.

### Concatenando 1-D

In [17]:
D11 = np.array([
    "Cloreto de Berílio",
    "Fluoreto de Berílio",
    "Oxido de Berílio",
    "Sulfato de Berílio"
])
D11.ndim

1

In [18]:
D12 = np.array([
    "BeCl2",
    "BeF2",
    "BeO",
    "BeSO4"
])
D12.ndim

1

In [19]:
D13 = np.concatenate(([D11],[D12]),axis=0)
D13

array([['Cloreto de Berílio', 'Fluoreto de Berílio', 'Oxido de Berílio',
        'Sulfato de Berílio'],
       ['BeCl2', 'BeF2', 'BeO', 'BeSO4']], dtype='<U19')

In [20]:
D13.ndim

2

In [21]:
print(D13)

[['Cloreto de Berílio' 'Fluoreto de Berílio' 'Oxido de Berílio'
  'Sulfato de Berílio']
 ['BeCl2' 'BeF2' 'BeO' 'BeSO4']]


In [22]:
D133 = np.stack((D11,D12), axis=1)
D133

array([['Cloreto de Berílio', 'BeCl2'],
       ['Fluoreto de Berílio', 'BeF2'],
       ['Oxido de Berílio', 'BeO'],
       ['Sulfato de Berílio', 'BeSO4']], dtype='<U19')

In [23]:
D133.ndim

2

In [24]:
SD1 = np.hstack((D11,D12))
SD1

array(['Cloreto de Berílio', 'Fluoreto de Berílio', 'Oxido de Berílio',
       'Sulfato de Berílio', 'BeCl2', 'BeF2', 'BeO', 'BeSO4'],
      dtype='<U19')

In [25]:
SD2 = np.vstack((D11,D12))
SD2

array([['Cloreto de Berílio', 'Fluoreto de Berílio', 'Oxido de Berílio',
        'Sulfato de Berílio'],
       ['BeCl2', 'BeF2', 'BeO', 'BeSO4']], dtype='<U19')

In [26]:
SD2.ndim

2

In [27]:
SD3 = np.dstack((D11,D12))
SD3

array([[['Cloreto de Berílio', 'BeCl2'],
        ['Fluoreto de Berílio', 'BeF2'],
        ['Oxido de Berílio', 'BeO'],
        ['Sulfato de Berílio', 'BeSO4']]], dtype='<U19')

In [28]:
SD3.ndim

3

In [29]:
import csv

In [30]:
with open('abc - Página1.csv') as file:
    reader = csv.reader(file)
    rows = list(reader)
    print(rows,end="\n\n")
    a = np.transpose(rows)
    print(a)


[['Número', '1', '2', '3', '4'], ["H2O'", '0,094', '0,162', '0,255', '0,436'], ['CHCl3', '0,254', '0,753', '1,827', '5,462']]

[['Número' "H2O'" 'CHCl3']
 ['1' '0,094' '0,254']
 ['2' '0,162' '0,753']
 ['3' '0,255' '1,827']
 ['4' '0,436' '5,462']]


In [31]:
print(a.shape[0])
print(a.shape[1])

5
3


## Equação balanceada pelo método de escalonamento

Usando numpy para balancear uma equação química, formando um sistema linear de equações.
Na equação de combustão do Cicloexanotiol, um sistema de equações é criado. utilizando o método de eleminação Gauss-Jordan.
$$C_6H_{12}S+O_2 \to H_2CO_3+SO_2$$


Assumindo que os coeficiente estequiométricos são $X_1,X_2,X_3,X_4$

$$x_1(C_6H_{12}S)+x_2(O_2) \to x_3(H_2CO_3)+x_4(SO_2)$$

A ordem dos elementos:

1. C
2. H
3. O
4. S


$$x_1\begin{pmatrix} 6\\12\\0\\1\end{pmatrix}+x_2\begin{pmatrix}0\\0\\2\\0 \end{pmatrix}=
x_3\begin{pmatrix}1\\2\\3\\0 \end{pmatrix}+x_4\begin{pmatrix}0\\0\\2\\1 \end{pmatrix}$$


$C: 6x_1=x_3 \text{ ou } 6x_1-x_3=0$


$H: 12x_1=2x_3$


$O: 2x_2=3x_3+2x_4$

$S: x_1=x_4$


Montando as equações:
$$6x_1+0x_2-x_3-0x_4=0$$

$$12x_1+0x_2-2x_3-0x_4=0$$

$$0x_1+2x_2-3x_3-2x_4=0$$

$$x_1+0x_2-0x_3-x_4=0$$


$$\begin{bmatrix}6&0&-1&0\\12&0&-2&0\\0&2&-3&-2\\1&0&0&-1 \end{bmatrix}$$

In [32]:
def re(M,v=0):
    a,b = M.shape
    x,y = 0,0
    M1 = []

    while x < a and y < b:
        #index of largest element in the remainder of column y
        k =np.argmax(np.abs(M[x:a,y])) + x
        p = np.abs(M[k,y])
        if p <= v:
            #the column is negligible, zero it out
            M[x:a,y] = 0.0
            y += 1
        else:
            M1.append(y)
            if x != k:
                #exchange x & y rows
                M[[x,k],y:b] = M[[k,x],y:b]
                #divide row x by the element M[x,y]
            M[x,y:b] = M[x, y:b] / M[x,y]

            #subtracting multiplies of pivot row from all other rows
            for k in range(a):
                if k != x:
                    M[k, y:b] -= M[k,y] * M[x,y:b]
            x += 1
            y += 1
    return M, M1 # at the indent of while




In [33]:
M =  np.array([
    [6,0,-1,0],
    [12,0,-2,0],
    [0,2,-3,-2],
    [1,0,0,-1]
],dtype=np.float_)
M

array([[ 6.,  0., -1.,  0.],
       [12.,  0., -2.,  0.],
       [ 0.,  2., -3., -2.],
       [ 1.,  0.,  0., -1.]])

In [34]:
Mred, M1 = re(M)
print(Mred)

[[  1.   0.   0.  -1.]
 [  0.   1.   0. -10.]
 [  0.   0.   1.  -6.]
 [  0.   0.   0.   0.]]


$$x_1 -1 = 0$$

$$x_2 -10 =0$$

$$x_3 - 6 = 0$$

$x_1 = 1$

$x_2 = 10$

$x_3 = 6$

$x_4 = x_1$

$$1C_6H_{12}S+10(O_2) \to 6H_2CO_3+1SO_2$$

## ChemPy

Usado para:
- calcular massa molar
- estequiometria


Mostra as funções no formato LaTeX, unicode e .html

In [35]:
from chempy import Substance

In [36]:
x = Substance.from_formula('HCl')

In [37]:
x.mass

36.458000000000006

### LaTex, Unicode e Html


As funções `.unicode_name`  , `.latex_name` e `.html_name` retorna Latex, unicode e .html

In [38]:
x1 =  Substance.from_formula('FeSO4')

In [39]:
x1.unicode_name

'FeSO₄'

In [40]:
x1.latex_name

'FeSO_{4}'

In [41]:
x1.html_name

'FeSO<sub>4</sub>'

## Balanceando equações

Equações químicas podem ser balanceadas baseadas nas funções `balance_stoichiometry({Reactants}, {Products})` e pode ser importado como  `from chempy import balance_stoichiometry`

$$2K_3Fe(CN)_6+6H_2SO_4 \to 3K_2SO_4 + Fe_2(SO_4)_3+12HCN$$

In [42]:
from chempy import balance_stoichiometry

In [43]:
R1 = "K3Fe(CN)6"
R2 = "H2SO4"
P1 = "K2SO4"
P2 = "Fe2(SO4)3"
P3 = "HCN"

In [44]:
reactants, products =  balance_stoichiometry({R1,R2},{P1,P2,P3})

In [45]:
print(reactants)
print(products)

OrderedDict([('H2SO4', 6), ('K3Fe(CN)6', 2)])
OrderedDict([('Fe2(SO4)3', 1), ('HCN', 12), ('K2SO4', 3)])


In [46]:
type(reactants)

collections.OrderedDict

## Mendeleev


Para dados atómicos e iônicos.

In [48]:
from mendeleev import element

In [51]:
element(27).density

8.86

In [52]:
element("Fe").molar_heat_capacity

25.1

In [53]:
element("Si").phase_transitions

[14 Tm=1687.15 Tb=3538.15]

In [57]:
element("Cl").electron_affinity

3.612725

In [58]:
element("Mn").description

'Grey brittle metallic transition element. Rather electropositive, combines with some non-metals when heated. Discovered in 1774 by Scheele.'

In [59]:
element("Sm").ec

<ElectronicConfiguration(conf="1s2 2s2 2p6 3s2 3p6 4s2 3d10 4p6 5s2 4d10 5p6 4f6 6s2")>

In [60]:
element("Os").econf

'[Xe] 4f14 5d6 6s2'

In [61]:
element("N").oxistates

[-3, 3, 5]