# Criptografia de Mensagens

Codificar e decodificar mensagens usando matrizes, basicamente uma matriz quadrada A e de sua inversa para fazermos a criptografia.

In [1]:
import numpy as np

In [2]:
C = np.array(([1,2],[3,4]))
D = np.linalg.inv(C)
D

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
#dicionário para referencia dos números com as letras
cod = {
    1:'A',2:'B',3:'C',4:'D',5:'E',6:'F',7:'G',8:'H',9:'I',10:'J',11:'L',12:'K',13:'M',
    14:'N',15:'O',16:'P',17:'Q',18:'R',19:'S',20:'T',21:'U',22:'V',23:'W',24:'X',25:'Y',26:'Z',27:'-',28:',',29:'_'
}

In [12]:
def texto2numero(texto):
    nu = []
    if (len(texto)%2 != 0):
        texto = texto+'_'
        print('É preciso adicionar "_" pra completar a matriz')
    for ii in texto:
        for j in cod:
            if (cod[j]==ii):
                nu.append(j)
    return nu

In [13]:
def numero2texto(num):
    tex = ''
    for i in num:
        tex = tex + str(cod[round(i)])
    return tex

In [42]:
texto = "SERA_QUE_FUNCIONA_MESMO"
VT = texto2numero(texto)
MT =  np.array(VT)
MSG = MT.reshape(2,int(MT.size/2))
MC = C.dot(MSG)
MD = D.dot(MC)
msg_d = MD.reshape(1,MD.size)

É preciso adicionar "_" pra completar a matriz


In [44]:
# vetor
print(VT)

[19, 5, 18, 1, 29, 17, 21, 5, 29, 6, 21, 14, 3, 9, 15, 14, 1, 29, 13, 5, 19, 13, 15, 29]


In [46]:
# convertido à matriz
MT

array([19,  5, 18,  1, 29, 17, 21,  5, 29,  6, 21, 14,  3,  9, 15, 14,  1,
       29, 13,  5, 19, 13, 15, 29])

In [49]:
# matriz de 2x12
MSG.shape

(2, 12)

In [52]:
# mesnagem criptografada
MC

array([[ 25,  23,  48,  29,  31,  75,  47,  15,  67,  32,  51,  72],
       [ 69,  51, 114,  59,  91, 167, 115,  35, 163,  70, 123, 158]])

In [53]:
# mensagem decriptografada
MD 

array([[19.,  5., 18.,  1., 29., 17., 21.,  5., 29.,  6., 21., 14.],
       [ 3.,  9., 15., 14.,  1., 29., 13.,  5., 19., 13., 15., 29.]])

In [58]:
# mensagem decriptografada remodelada à matriz de 1x
msg_d

array([[19.,  5., 18.,  1., 29., 17., 21.,  5., 29.,  6., 21., 14.,  3.,
         9., 15., 14.,  1., 29., 13.,  5., 19., 13., 15., 29.]])

In [80]:
msg_d[0,0] == MT[0]

True

In [73]:
print(msg_d[0])

[19.  5. 18.  1. 29. 17. 21.  5. 29.  6. 21. 14.  3.  9. 15. 14.  1. 29.
 13.  5. 19. 13. 15. 29.]
